// // app/login/layout.tsx
// import { ReactNode } from 'react';
// import { MantineProvider } from '@mantine/core';
// import { theme } from '@/src/styles/theme';
// export default function AuthLayout({ children }: { children: ReactNode }) {
//   return (
//     <MantineProvider theme={theme}>
//       <div className="flex min-h-screen items-center justify-center bg-gray-500">
//         <div className="w-full max-w-md rounded-lg bg-white p-6 shadow-lg">{children}</div>
//       </div>
//     </MantineProvider>
//   );
// }
import type { Metadata } from 'next';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import ClientProvider from '@/src/components/client-provider';
import Header from '@/src/components/common/header/container';
import { pretendard } from '@/src/fonts/pretendard/pretendard';
import '@/src/styles/globals.css';
import { theme } from '@/src/styles/theme';

export const metadata: Metadata = {
  title: 'CrewCrew',
  description: 'Generated by CODEIT TEAM1',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <head>
        <ColorSchemeScript />
      </head>

      <body className="flex min-h-screen flex-col bg-gray-50">
        <ClientProvider>
          <MantineProvider theme={theme}>
            <Header />
            <div className="flex min-h-screen items-center justify-center bg-gray-500">
              <div className="w-full max-w-md rounded-lg bg-white p-6 shadow-lg">{children}</div>
            </div>
          </MantineProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
