import type { Metadata } from 'next';
import Image from 'next/image';
import '@mantine/core/styles.css';
import Header from '@/src/components/common/header/container';
import '@/src/styles/globals.css';
import Auth from '@/public/assets/images/auth.png';

export const metadata: Metadata = {
  title: 'CrewCrew',
  description: 'Generated by CODEIT TEAM1',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen flex-col bg-gray-50">
      <Header />
      <div className="flex flex-1">
        <div className="hidden h-full w-2/3 items-center md:flex">
          <Image src={Auth} alt="auth" />
        </div>
        <div className="flex h-full w-full bg-white md:w-1/3 md:items-center">{children}</div>
      </div>
    </div>
  );
}
