name: Trigger Fork Repo Action - develop
on:
  push:
    branches:
      - develop
jobs:
  trigger-fork:
    if: github.repository_owner == 'CodeitFESI4-Team1'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch - develop
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.CREWCREW }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/yulrang/Team-1-Codeit-youl/dispatches" \
          -d '{"event_type": "develop_updated"}'
